from subprocess import call, Popen, PIPE
import re

configfile: "config.yml"

rule all:
	input:
		#"output/BOLD/bold_all_sequences_taxonomy.fa",
		#"output/BOLD/bold_all_taxonomy.tsv",
		#"simplecheck_bold_taxonomy_log.txt"
		"output/BOLD/bold_all_sequences_taxonomy.fa"

rule bold:
	output:
		"output/BOLD/bold_all_sequences_taxonomy.fa"
	params:
		arthropoda_fasta=config["arthropoda"]["fasta"],
		arthropoda_taxonomy=config["arthropoda"]["taxonomy"]
	run:
		shell("sh get_bold_sequences.sh output/bold_fasta_files")
		#Arthropoda fasta file is a known problem
		shell("rm -f output/bold_fasta_files/Arthropoda_sequences.fasta")
		#Copy manual downloaded Arthropoda fasta file to download folder
		shell("cp {params.arthropoda_fasta} output/bold_fasta_files/Arthropoda_sequences_manual.fasta")
		shell("cat output/bold_fasta_files/* > output/BOLD/bold_all_sequences.fa")
		shell("sh get_bold_taxonomy.sh output/bold_taxonomy_files")
		#Arthropoda taxonomy file is a known problem
		shell("rm -f output/bold_taxonomy_files/Arthropoda_taxonomy.tsv")
		shell("cp {params.arthropoda_taxonomy} output/bold_taxonomy_files/Arthropoda_taxonomy_manual.tsv")
		shell("cat output/bold_taxonomy_files/* > output/BOLD/bold_all_taxonomy.tsv")
		#The BOLD API can give strange output, this is a quick check for that
		shell("sh simplecheck_bold_sequences.sh output/bold_fasta_files output/simplecheck_bold_sequences_log.txt")
		shell("sh simplecheck_bold_taxonomy.sh output/bold_taxonomy_files output/simplecheck_bold_taxonomy_log.txt")
		shell("sed -e '/^[^>]/ s/-//g' output/BOLD/bold_all_sequences.fa > output/BOLD/bold_all_sequences_filtered.fa")
		shell("awk -F \"\t\" '{{print $1\"\t\"$10\"\t\"$12\"\t\"$14\"\t\"$16\"\t\"$20\"\t\"$22}}' output/BOLD/bold_all_taxonomy.tsv > output/BOLD/bold_all_taxonomy_filtered.tsv")
		shell("wget -P output/BOLD http://rs.gbif.org/datasets/backbone/backbone-current.zip")
		shell("unzip -j output/BOLD/backbone-current.zip \"Taxon.tsv\"")
		shell("awk -F \"\t\" '{{print $18\"\t\"$19\"\t\"$20\"\t\"$21\"\t\"$22\"\t\"$23}}' output/BOLD/Taxon.tsv > output/BOLD/gbif_taxonomy.tsv")
		shell("python add_taxonomy_bold.py -t output/BOLD/bold_all_taxonomy_filtered.tsv -g output/BOLD/gbif_taxonomy.tsv -b output/BOLD/bold_all_sequences_filtered.fa -o output/BOLD/bold_all_sequences_taxonomy.fa")

		#Do not uncomment these lines while developing
		#shell("rm -rf bold_fasta_files")
		#shell("rm -rf bold_taxonomy_files")
